config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :topics #do
    resource  :interests
  # end

  root to: 'topics#index'

  get 'search', to: 'topics#search'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many   :interests
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics
  has_many :interests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.email        = auth.info.email
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.password     = Devise.friendly_token[0,20]
    user.save!

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :authenticate_user!

  def create
    @interest = Interest.new(interest_params)
    @interest.user_id = current_user.id
    @interest.topic_id = (params[:topic_id])

    @topic = Topic.find_by('id = ?', @interest.topic_id)
    unless @interest.rating == nil
      @topic.score += @interest.rating
    end
    @topic.comment_count += 1

    @interest.save
    @topic.save

    redirect_to topics_path
  end

private
  def interest_params
    params.require(:interest).permit(:rating, :comment, :topic_id)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update]

  def index
    @topic = Topic.all.order(score: :desc)
  end

  def new
    @topic = Topic.new
  end

  def search
    found = params[:title]
    # use this line for sqlite db
    # @topic = Topic.where("title like ?", "%#{found}%")

    # use this line for postgres db
    @topic = Topic.where("title ilike ?", "%#{found}%")
  end

  def show
    @commented = current_user.interests.where("topic_id = ?", @topic.id)
    @rated = @commented.where("rating is not null")
    @interest = Interest.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.save

    redirect_to topics_path
  end

  def update
    @topic.update(topic_params)

    redirect_to topics_path
  end

private
  def topic_params
    params.require(:topic).permit(:title, :description, :focus)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to topics_path, notice: "ERROR::FILE NOT FOUND"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, target-densitydpi=device-dpi, initial-scale=1, user-scalable=no" }
    %title IronTopics
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= #alert

    = yield

app/views/topics/_edit.html.haml
:javascript
  $('#cancel').click(function(){
  var id = $(this).data('topic-id');
  $.ajax('/topics/' + id, {
  method: 'GET',
  });
  });

#edit_form
  #update
    = render 'form'
    .cancel
      %button#cancel{ 'data-topic-id': "#{@topic.id}"} CANCEL

app/views/topics/_form.html.haml
= form_for(@topic) do |f|
  #add_field
    = f.text_field :title, placeholder: " Title"
    = f.text_field :description, placeholder: " Description"
    = f.text_field :focus, placeholder: " Focus area"
    #topic_submit= f.submit

app/views/topics/_navbar.html.haml
#header
  %div
    #home-mini
      = link_to "", topics_path, method: :get, class:"glyphicon glyphicon-home"
    #home
      = link_to "_HOME", topics_path, method: :get, class:"glyphicon glyphicon-home"
      #search
        %input.to_search{ type: "text", placeholder: " Search", data_remote: "true" }
    %h3
      = image_tag("tiy.png", size: "65x65")
      IRON TOPICS
    #logout-mini
      = link_to "", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out"
    #logout
      = link_to destroy_user_session_path, method: :delete do
        %span.glyphicon.glyphicon-log-out _LOGOUT

#spacer

app/views/topics/_new.html.haml
= render 'form'

app/views/topics/_show.html.haml
:javascript
  var textContainer, textareaSize, input;
  var autoSize = function () {
    textareaSize.innerHTML = input.value + '\n';
  };

  textContainer = document.querySelector('.textarea-container');
  textareaSize = textContainer.querySelector('.textarea-size');
  input = textContainer.querySelector('textarea');

  autoSize();
  input.addEventListener('input', autoSize);

  $('#edit').click(function(){
  console.log("I clicked to EDIT")
  $(".modal-content").html("");
  var id = $(this).data('topic-id');
  console.log(id)
  $.ajax('/topics/' + id + '/edit', {
  method: 'GET',
  });
  });

.comment_page
  #topic
    #topics
      .topic_listing
        #no_pointer
          .thing_holder
            .thing1=topic.focus
            .thing2
              interest score
              %span= topic.score
          %p#no_decor= topic.title
        .edit
          - unless topic.comment_count > 0 || topic.user_id != current_user.id
            .edit_link#edit{ 'data-topic-id': "#{topic.id}" } edit
            -# .edit_link#edit= link_to "edit", edit_topic_path(topic)

    #ratings.well.well-sm
      %div{style: "text-decoration: underline"}
        =topic.user.name
        says:
      #description= topic.description
      - @topic.interests.each do |interest|
        #user_rating
          %span.name= interest.user.name
          %span.rating
            - if interest.rating
              - (5 - interest.rating).times do
                .glyphicon.glyphicon-ok-sign#minus_rating
              - interest.rating.times do
                .glyphicon.glyphicon-ok-sign#star_rating
            - else
              - 5.times do
                .glyphicon.glyphicon-ok-sign#minus_rating
        .comment= interest.comment
      %div
        = form_for(@interest) do |f|
          .field
            - if @rated != []
              - 5.times do
                #blank.glyphicon.glyphicon-ok-sign
            - else
              = f.hidden_field :rating, class: "rating form_control"
              %span.rating_text
                \- rate this topic?
            .textarea-container
              = f.text_area :comment, placeholder: ' type your comment here'
              .textarea-size
            = hidden_field_tag :topic_id, @topic.id
            = f.submit "Comment"

app/views/topics/_topic.html.haml
.topic_listing{ id: "topic_listing_#{topic.id}", 'data-topic-id': "#{topic.id}", 'data-toggle': "modal", 'data-target': ".bs-example-modal-lg" }
  %div
    .thing_holder
      .thing1=topic.focus
      .thing2
        interest score
        %span= topic.score
    %p= topic.title

  .edit
    - unless topic.comment_count > 0 || topic.user_id != current_user.id
      .edit_link editable

app/views/topics/edit.js.erb
$(".modal-content").html( $("<%= escape_javascript(render partial: 'edit') %>") )

app/views/topics/index.html.haml
= render 'navbar'
#add_topic-mini
  .add_link{ 'data-toggle': "modal", 'data-target': ".bs-example-modal-lg"}
    \ Add a new topic
  #search-mini
    %input.to_search{ type: "text", placeholder: " Search", 'data-remote': "true" }
%p#add_topic
  Have a topic you want reviewed?
  %span.add_link{ 'data-toggle': "modal", 'data-target': ".bs-example-modal-lg"}
    \ Let's talk about it!
  %span#search-mini
    %input.to_search{ type: "text", placeholder: " Search", 'data-remote': "true" }

#topics
  = render @topic

.modal.fade.bs-example-modal-lg{tabindex: "-1", role:"dialog", aria_labelledby: "myLargeModalLabel"}
  .modal-dialog.modal-lg
    .modal-content

app/views/topics/new.js.erb
$(".modal-content").html( $("<%= escape_javascript(render partial: 'new', locals: { topic: @topic }) %>") )

app/views/topics/search.js.erb
$("#topics").html( $("<%= escape_javascript(render @topic) %>") )

app/views/topics/show.js.erb
// Create a bootstrap modal, fill it with the html from erb, show the modal
$(".modal-content").html( $("<%= escape_javascript(render partial: 'show', locals: { topic: @topic }) %>") )
$('.modal-content input.rating').each(function() {
  $(this).rating();
});